name: Thulani01 test 01 and Report with CML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up CML
        uses: iterative/setup-cml@v2

      - name: Train model
        run: |
          pip install -r requirements.txt
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Results" > report.md
          if [ -f results.txt ]; then
            cat results.txt >> report.md
          else
            echo "⚠️ No results.txt file found from training step." >> report.md
          fi
          cml comment create report.md

          # Post reports as comments in GitHub PRs
          # Append any extra metrics file
          if [ -f metrics.txt ]; then
          cat metrics.txt >> report.md
          fi

          # Publish and embed images (returns a markdown link we append)
          if [ -f feature_importance.png ]; then
          echo "" >> report.md
          echo "![Feature Importance](feature_importance.png)" >> report.md

          fi

          if [ -f residuals_importance.png ]; then
          echo "" >> report.md
          echo "![Residuals vs. Predicted](residuals_importance.png)" >> report.md

          fi

          # Finally, post the markdown file as a comment
          cml comment create report.md
    

