name: Train and Report with CML
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # allow commit comments
      pull-requests: write   # allow PR comments
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1

      - name: Train model
        run: |
          pip install -r requirements.txt
          python train.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat metrics.txt >> report.md
          cml comment create report.md

          echo "##Data viz" >> report.md
          cml -publish feature_importance.png -- md >> report.md
          cml -publish residuals_importance.png -- md >> report.md
          cml-send-commet report.md

